myblog/blog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^posts/(?P<slug>[\w-]+)/$', views.detail, name='detail'),
    url(r'^posts/$', views.year_archive, name='archive'),
    url(r'^tags/(?P<slug>[\w-]+)/$', views.tag_detail, name='tag_detail'),
    url(r'^tags/$', views.tags, name='tags'),
    url(r'about/$', views.about, name='about'),
]

myblog/myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('blog.urls', namespace='blog')),
]

myblog/blog/models.py
import collections
from operator import attrgetter

from django.db import models
from django.urls import reverse
from model_utils.models import TimeStampedModel


class PublishedPostManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(publish=True)

    def recent_posts(self, number):
        return self.get_queryset().all()[:number]

    def year_carchive(self):
        dd = collections.defaultdict(list)
        for post in self.get_queryset():
            dd[post.created.year].append(post)
        return [(year, dd[year]) for year in sorted(dd)]


class TagManager(models.Manager):
    def ordered_by_capacity(self):
        tags = self.get_queryset()
        return sorted(list(tags), key=attrgetter('capacity'), reverse=True)


class Tag(TimeStampedModel):
    name = models.CharField(max_length=16, unique=True)
    slug = models.SlugField()

    objects = TagManager()

    @property
    def capacity(self):
        return self.post_set.count()

    class Meta:
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('blog:tag_detail', args=[self.slug])

    def __str__(self):
        return self.name


class Post(TimeStampedModel):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField()
    content = models.TextField()
    publish = models.BooleanField(default=True)
    tags = models.ManyToManyField(Tag, blank=True)

    objects = models.Manager()
    published = PublishedPostManager()

    class Meta:
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('blog:detail', args=[self.slug])

    def __str__(self):
        return 'Post<{}>'.format(self.title)


class About(models.Model):
    content = models.TextField(verbose_name='About myself')

myblog/blog/views.py
from django.shortcuts import render

from .models import Post, About, Tag


def index(request):
    return render(request, 'blog/index.html', {
        'posts': Post.published.recent_posts(5),
    })


def detail(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'blog/detail.html', {
        'post': post,
    })


def year_archive(request):
    return render(request, 'blog/year_archive.html', {
        'year_posts': Post.published.year_carchive(),
    })


def tags(request):
    return render(request, 'blog/tags.html', {
        'tags': Tag.objects.ordered_by_capacity(),
    })


def tag_detail(request, slug):
    tag = Tag.objects.get(slug=slug)
    return render(request, 'blog/tag_detail.html', {
        'tag': tag,
        'posts': tag.post_set.all(),
    })


def about(request):
    about = About.objects.first().content
    return render(request, 'blog/about.html', {'about': about})

myblog/blog/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1"/>
    <meta name="generator" content="iron"/>
    <meta name="viewport" content="width=device-width,initial-scale=1"/>
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=RobotoDraft:300,400|Inconsolata:400,700"/>
    <link rel="stylesheet" type="text/css" href="{% static "main.css" %}"/>
    <link rel="shortcut icon" type="image/x-icon" href="{% static "img/favicon.ico" %}" />

    <title>
      {% block title %} keep simple {% endblock title %}
    </title>

  </head>

  <body class="home">
    <div class="site-container">
      <div class="site-header">
        <nav>
          <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/posts/">Posts</a></li>
            <li><a href="/tags/">Tags</a></li>
            <li><a href="/about/">About</a></li>
          </ul>
        </nav>

        <header>
          {% block header %}
          {% endblock header %}
        </header>
      </div>

      <article>
        {% block article %}
        {% endblock article%}
      </article>

    </div>

    <footer>
      <div id="footer">
        {% block footer %}
        <p>
          Keep Simple &amp; Live Happily
        </p>
        {% endblock footer %}

      </div>
    </footer>

  </body>
</html>

myblog/blog/templates/blog/about.html
{% extends "base.html" %}

{% load markdown_deux_tags %}

{% block title %}About me &raquo; keep simple{% endblock title %}

{% block header %}
<h1>About me</h1>

<div class="tagline">
  Who's behind this blog?
</div>

{% endblock header %}

{% block article %}

{{ about|markdown }}

{% endblock article %}

myblog/blog/templates/blog/detail.html
{% extends "base.html" %}

{% load staticfiles %}
{% load markdown_deux_tags %}

{% block title %}{{ post.title }} &raquo; keep simple{% endblock title %}

{% block header %}
<h1>{{ post.title }}</h1><br>

  <div class="meta">
    <small>
    By <a href="{% url "blog:about" %}">Luo Jiebin</a><br>
    on {{ post.created|date:"l, M d, Y"}}
    </small>
  </div>

{% endblock header %}

{% block article %}

  <div class="post">{{ post.content|markdown }}</div>

{% endblock article %}


</article>

myblog/blog/templates/blog/index.html
{% extends "base.html" %}

{% block header %}
<h1>keep simple</h1>

<div class="tagline">
  Thoughts and writtings by Luo Jiebin.
</div>
{% endblock header%}

{% block article %}
{% for post in posts %}
<div class="post-entry">
  <div class="post-detail">
    <h2>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
      <span class="post-date">{{ post.created|date:"M d, Y" }}</span>
    </h2>
  </div>
</div>
{% endfor %}


<h2 class="readmore">
  <a href="{% url "blog:archive" %}">Read more posts &raquo;</a>
</h2>

{% endblock article %}

{% block footer %}
{% endblock footer %}

myblog/blog/templates/blog/tag_detail.html
{% extends "base.html" %}

{% block header %}
<h1>{{ tag.name }}</h1>

<div class="tagline">
  Thoughts and writtings by Tag: {{ tag.name }}.
</div>
{% endblock header%}

{% block article %}
{% for post in posts %}

<div class="post-entry">
  <div class="post-detail">
    <h2>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
      <span class="post-date">{{ post.created|date:"M d, Y" }}</span>
    </h2>
  </div>
</div>
{% endfor %}

{% endblock article %}

myblog/blog/templates/blog/tags.html
{% extends "base.html" %}

{% block title %}Tags &raquo; keep simple{% endblock title %}

{% block header %}
<h1>Tags</h1>
<div class="tagline">
  All tags to group thoughts and writtings.
</div>
{% endblock header %}

{% block article %}
<div>
  {% for tag in tags %}
  <div class="tag-entry">
    <div class="tag-detail">
      <h2>
        <a href="{{ tag.get_absolute_url }}">{{ tag.name }}</a>
      </h2>
    </div>
  </div>
  {% endfor %}
{% endblock article %}

myblog/blog/templates/blog/year_archive.html
{% extends "base.html" %}

{% block title %}Archive &raquo; keep simple{% endblock title %}

{% block header %}
<h1>Archive</h1>
<div class="tagline">
  All thoughts and writings.
</div>
{% endblock header %}

{% block article %}
{% for year, posts in year_posts %}
<h1 class="year">{{ year }}</h1>
<div>
  {% for post in posts %}
  <div class="post-entry">
    <div class="post-detail">
      <h2>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        <span class="post-date">{{ post.created|date:"M d, Y" }}</span>
      </h2>
    </div>
  </div>
  {% endfor %}
  {% endfor %}
{% endblock article %}